characters = [
  "Sol Badguy",
  "Ky Kiske",
  "May",
  "Axl Low",
  "Chipp Zanuff",
  "Potemkin",
  "Faust",
  "Millia Rage",
  "Zato-1",
  "Giovanna",
  "Ramlethal Valentine",
  "Leo Whitefang",
  "Nagoriyuki",
  "Anji Mito",
  "I-No",
  "Goldlewis Dickinson",
  "Jack-O'",
  "Happy Chaos",
  "Baiken",
  "Testament",
  "Bridget",
  "Sin Kiske",
  "Bedman?",
  "Asuka R#",
  "Johnny",
  "Elphelt Valentine",
  "A.B.A.",
  "Slayer",
  "Queen Dizzy",
  "Venom",
  "Unika",
  "Lucy Kushinada"
]